# Basic Stuff
title = "Subho Sankar Banerjee"
googleAnalytics = "UA-48086103-1"
baseURL = "https://ssbaner2.cs.illinois.edu"
languageCode = "en-us"
enableRobotsTXT = true

# Taxonomies
disableKinds = ["term","taxonomy"]

# Markdown & Rendering
buildFuture = true
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    guessSyntax = true
    style = "manni"

# Site parameters
[params]
  showFeatured = true

# SEO Stuff
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

