# Basic Stuff
title = "Subho Sankar Banerjee"
googleAnalytics = "UA-48086103-1"

# URLs
baseURL = "http://ssbaner2.cs.illinois.edu"
languageCode = "en-us"

# Taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

# Render settings
pygmentsCodeFences = true
pygmentsStyle = "manni"

# Custom taxonomies
[taxonomies]
  pubtype = "pubtypes"
  project = "projects"

# Markdown Rendering
[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
  latexDashes = true
  hrefTargetBlank = true

# Site parameters
[params]
  name = "Subho Sankar Banerjee"
  description = "Subho Banerjee's Homepage"
  position = "PhD Candidate"
  department = "Computer Science"
  univeristy = "University of Illinois at Urbana-Champaign"
  avatar = "img/me_sq.png"
  email = "ssbaner2@illinois.edu"
  address = "CSL 240"
  address_url = "http://illinois.edu/map/view?buildingId=148"
  linkedin = "https://www.linkedin.com/in/ssbanerjee/"
  github = "https://github.com/ssbanerje"
  dblp = "https://dblp.uni-trier.de/pers/hd/b/Banerjee:Subho_S="
  orcid = "0000-0001-7187-6569"

# SEO Stuff
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
