# Basic Stuff
title = "Subho Sankar Banerjee"
googleAnalytics = "UA-48086103-1"

# URLs
baseURL = "http://ssbaner2.cs.illinois.edu"
languageCode = "en-us"

# Taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

# Render settings
pygmentsCodeFences = true
pygmentsUseClassic=true
pygmentsStyle = "manni"
pygmentsOptions = "linenos=true,nowrap=false"

# Custom taxonomies
[taxonomies]
  pubtype = "pubtypes"
  project = "projects"

# Markdown Rendering
[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
  latexDashes = true

# Site parameters
[params]
  name = "Subho Sankar Banerjee"
  position = "PhD Candidate"
  department = "Computer Science"
  univeristy = "University of Illinois at Urbana-Champaign"
  avatar = "img/me_sq.png"
  email = "ssbaner2@illinois.edu"
  address = "CSL 240"
  address_url = "http://illinois.edu/map/view?buildingId=148"
  linkedin = "https://www.linkedin.com/in/ssbanerjee/"
  github = "https://github.com/ssbanerje"
  dblp = "https://dblp.uni-trier.de/pers/hd/b/Banerjee:Subho_S="
  orcid = "0000-0001-7187-6569"
  sidebar_color = "#141f33"
  sidebar_link_color = "#fff"
  sidebar_linkhover_color = "#fff2e5"
  text_color = "#333"
  text_link_color = "#274798"
  text_linkhover_color = "#f16421"
