# Basic Stuff
title = "Subho Sankar Banerjee"
googleAnalytics = "UA-48086103-1"

# URLs
baseURL = "http://ssbaner2.web.engr.illinois.edu"
languageCode = "en-us"

# Render settings
pygmentsCodeFences = true
pygmentsStyle = "colorful"
disableKinds = ["taxonomy","taxonomyTerm"]

[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
  latexDashes = true

[params]
  name = "Subho Sankar Banerjee"
  position = "PhD Candidate"
  department = "Computer Science"
  univeristy = "University of Illinois at Urbana-Champaign"
  affiliation = "CS@Illinois"
  email = "ssbaner2@illinois.edu"
  address = "CSL 240"
  address_url = "http://illinois.edu/map/view?buildingId=148"
  avatar = "img/me_sq.png"
  linkedin = "https://www.linkedin.com/in/ssbanerjee/"
  github = "https://github.com/ssbanerje"
  dblp = "https://dblp.uni-trier.de/pers/hd/b/Banerjee:Subho_S="
  orcid = "0000-0001-7187-6569"
